[workspace]
members = ["crates/*"]

[workspace.package]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = 'symbols'
lto = true
codegen-units = 1
opt-level = 's'

[workspace.dependencies]
tokio = {version = "1.29.1", features = ["macros", "rt-multi-thread"]}
reqwest = "0.11.18"
serde = "1.0.166"
serde_derive = "1.0.166"
serde_json = "1.0.100"
chrono = "0.4.26"
lazy_static = "1.4.0"