[workspace]
members = ["crates/*"]

[workspace.package]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = 'symbols'
lto = true
codegen-units = 1
# opt-level = 's'

[workspace.dependencies]
teloxide = {version = "0.12", features = ["macros", "ctrlc_handler"]}
tokio = {version = "1.29.1", features = ["macros", "rt-multi-thread"]}
reqwest = "0.11.18"
serde = {version = "1.0.166", features = ["derive"]}
serde_json = "1.0.100"
chrono = "0.4.26"
lazy_static = "1.4.0"
toml = "0.7.6"
