# `docker compose build` to build the image
# `docker compose up -d` to start and detach

version: "3"

services:
  bot:
    image: ntu_canoebot
    container_name: ntucanoebot
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/build.Dockerfile

      # args:
        # - teloxide_token=${TELOXIDE_TOKEN:?NO_TELOXIDE_API_TOKEN}
        # - rust_log=${RUST_LOG:?NO_RUST_LOG_LEVEL}
