# `docker compose build` to build the image
# `docker compose up -d` to start and detach

version: "3"

services:
  bot:
    image: ntu_canoebot
    container_name: ntucanoebot
    restart: on-failure
    tty: true
    build:
      context: .
      dockerfile: ./docker/build.Dockerfile

    volumes:
      - logs:/var/log/ntu_canoebot

volumes:
  logs:
    name: "ntu_canoebot_logs"
