[package]
name = "ntu_canoebot"
version = "0.1.0"
edition = "2021"
description = "bot core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = '0.4'
pretty_env_logger = '0.5.0'
toml = '0.7.4'
serde_json = '1.0.96'
bincode = '1.3.3'
inflate = '0.4.5'
deflate = '1.0.0'
base64 = '0.21.0'
lazy_static = '1.4.0'
async-trait = '0.1.68'

[dependencies.teloxide]
version = '0.12'
features = [
    'macros',
    'ctrlc_handler',
]

[dependencies.tokio]
version = '1.28.1'
features = [
    'rt-multi-thread',
    'macros',
]

[dependencies.serde]
version = '1.0.163'
features = ['derive']
