# Keys defined here MUST be assigned a valid value.
# Make a copy of this file, and rename it to:
# - botsettings.template.debug.toml (if you want to test with alternate settings)
# - botsettings.template.deploy.toml (must exist when deploying)

# set to true to use this config
# if debug and deploy both have this set to `true`, debug is used.
use = false


[canoebot]
apikey = "change this to your api key"
exco_chat = "change to exco chat id (numeric)"

# not strictly required
[canoebot.known_chats]
# chat_1 = 1234567890


[sheetscraper]
# if this field is not defined, it will default to 1970-01-01
# as specified in `botsettings.template.toml`.
# change to first day of 'new' attendance and program sheet.
changeover_date = 1970-01-01

# these are the variables that require substitution:
# - date_str
# - boatallo_no_date
# - trainingam_prog
paddling.format = "your paddling format"


# previous AY configuration
[sheetscraper.old]
attendance_sheet = "google sheets sheetid"
program_sheet = "google sheets sheetid"

# new AY configuration
[sheetscraper.new]
attendance_sheet = "google sheets sheetid"
program_sheet = "google sheets sheetid"


[formfiller]
form_id = "SCF google forms id"

# At least one required
[formfiller.particulars]
# full_name = 987654321
# "full name in quotes" = 987654321


# don't think this is used anymore
[traininglog]
form_id = ""


[events.daily.logsheet_prompt]
enable = false
time = 07:00:00

[events.daily.attendance_reminder]
enable = false
time = 19:00:00

[events.weekly.breakdown] # saturdays
enable = true
time = 22:30:00


# NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
[logger]
log_level = "INFO"
