[package]
name = "ntu_canoebot_attd"
version = "0.1.0"
edition = "2021"
description = "Attendance handler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
g_sheets = {path = "../g_sheets"}
